/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SetupRouteRouteImport } from './routes/setup/route'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as SetupTeamRouteImport } from './routes/setup/team'
import { Route as SetupReviewRouteImport } from './routes/setup/review'
import { Route as SetupOrganizationRouteImport } from './routes/setup/organization'
import { Route as SetupInventoryRouteImport } from './routes/setup/inventory'
import { Route as SetupImportRouteImport } from './routes/setup/import'
import { Route as SetupBrandingRouteImport } from './routes/setup/branding'
import { Route as AppSuppliersRouteImport } from './routes/_app/suppliers'
import { Route as AppProductsRouteRouteImport } from './routes/_app/products/route'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppProductsNewRouteRouteImport } from './routes/_app/products/new/route'
import { Route as AppProductsNewIndexRouteImport } from './routes/_app/products/new/index'
import { Route as AppProductsNewSuppliersRouteImport } from './routes/_app/products/new/suppliers'
import { Route as AppProductsNewReviewRouteImport } from './routes/_app/products/new/review'
import { Route as AppProductsNewInventoryRouteImport } from './routes/_app/products/new/inventory'
import { Route as AppProductsNewCustomersRouteImport } from './routes/_app/products/new/customers'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRouteRoute = SetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SetupTeamRoute = SetupTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SetupRouteRoute,
} as any)
const SetupReviewRoute = SetupReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => SetupRouteRoute,
} as any)
const SetupOrganizationRoute = SetupOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => SetupRouteRoute,
} as any)
const SetupInventoryRoute = SetupInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => SetupRouteRoute,
} as any)
const SetupImportRoute = SetupImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => SetupRouteRoute,
} as any)
const SetupBrandingRoute = SetupBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => SetupRouteRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRouteRoute = AppProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppProductsNewRouteRoute = AppProductsNewRouteRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProductsRouteRoute,
} as any)
const AppProductsNewIndexRoute = AppProductsNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsNewRouteRoute,
} as any)
const AppProductsNewSuppliersRoute = AppProductsNewSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppProductsNewRouteRoute,
} as any)
const AppProductsNewReviewRoute = AppProductsNewReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppProductsNewRouteRoute,
} as any)
const AppProductsNewInventoryRoute = AppProductsNewInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppProductsNewRouteRoute,
} as any)
const AppProductsNewCustomersRoute = AppProductsNewCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppProductsNewRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/setup': typeof SetupRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/products': typeof AppProductsRouteRouteWithChildren
  '/suppliers': typeof AppSuppliersRoute
  '/setup/branding': typeof SetupBrandingRoute
  '/setup/import': typeof SetupImportRoute
  '/setup/inventory': typeof SetupInventoryRoute
  '/setup/organization': typeof SetupOrganizationRoute
  '/setup/review': typeof SetupReviewRoute
  '/setup/team': typeof SetupTeamRoute
  '/setup/': typeof SetupIndexRoute
  '/products/new': typeof AppProductsNewRouteRouteWithChildren
  '/products/': typeof AppProductsIndexRoute
  '/products/new/customers': typeof AppProductsNewCustomersRoute
  '/products/new/inventory': typeof AppProductsNewInventoryRoute
  '/products/new/review': typeof AppProductsNewReviewRoute
  '/products/new/suppliers': typeof AppProductsNewSuppliersRoute
  '/products/new/': typeof AppProductsNewIndexRoute
}
export interface FileRoutesByTo {
  '/suppliers': typeof AppSuppliersRoute
  '/setup/branding': typeof SetupBrandingRoute
  '/setup/import': typeof SetupImportRoute
  '/setup/inventory': typeof SetupInventoryRoute
  '/setup/organization': typeof SetupOrganizationRoute
  '/setup/review': typeof SetupReviewRoute
  '/setup/team': typeof SetupTeamRoute
  '/': typeof AppIndexRoute
  '/setup': typeof SetupIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/products/new/customers': typeof AppProductsNewCustomersRoute
  '/products/new/inventory': typeof AppProductsNewInventoryRoute
  '/products/new/review': typeof AppProductsNewReviewRoute
  '/products/new/suppliers': typeof AppProductsNewSuppliersRoute
  '/products/new': typeof AppProductsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/setup': typeof SetupRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_app/products': typeof AppProductsRouteRouteWithChildren
  '/_app/suppliers': typeof AppSuppliersRoute
  '/setup/branding': typeof SetupBrandingRoute
  '/setup/import': typeof SetupImportRoute
  '/setup/inventory': typeof SetupInventoryRoute
  '/setup/organization': typeof SetupOrganizationRoute
  '/setup/review': typeof SetupReviewRoute
  '/setup/team': typeof SetupTeamRoute
  '/_app/': typeof AppIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/_app/products/new': typeof AppProductsNewRouteRouteWithChildren
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/products/new/customers': typeof AppProductsNewCustomersRoute
  '/_app/products/new/inventory': typeof AppProductsNewInventoryRoute
  '/_app/products/new/review': typeof AppProductsNewReviewRoute
  '/_app/products/new/suppliers': typeof AppProductsNewSuppliersRoute
  '/_app/products/new/': typeof AppProductsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/setup'
    | '/'
    | '/products'
    | '/suppliers'
    | '/setup/branding'
    | '/setup/import'
    | '/setup/inventory'
    | '/setup/organization'
    | '/setup/review'
    | '/setup/team'
    | '/setup/'
    | '/products/new'
    | '/products/'
    | '/products/new/customers'
    | '/products/new/inventory'
    | '/products/new/review'
    | '/products/new/suppliers'
    | '/products/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/suppliers'
    | '/setup/branding'
    | '/setup/import'
    | '/setup/inventory'
    | '/setup/organization'
    | '/setup/review'
    | '/setup/team'
    | '/'
    | '/setup'
    | '/products'
    | '/products/new/customers'
    | '/products/new/inventory'
    | '/products/new/review'
    | '/products/new/suppliers'
    | '/products/new'
  id:
    | '__root__'
    | '/setup'
    | '/_app'
    | '/_app/products'
    | '/_app/suppliers'
    | '/setup/branding'
    | '/setup/import'
    | '/setup/inventory'
    | '/setup/organization'
    | '/setup/review'
    | '/setup/team'
    | '/_app/'
    | '/setup/'
    | '/_app/products/new'
    | '/_app/products/'
    | '/_app/products/new/customers'
    | '/_app/products/new/inventory'
    | '/_app/products/new/review'
    | '/_app/products/new/suppliers'
    | '/_app/products/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SetupRouteRoute: typeof SetupRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/setup/team': {
      id: '/setup/team'
      path: '/team'
      fullPath: '/setup/team'
      preLoaderRoute: typeof SetupTeamRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/setup/review': {
      id: '/setup/review'
      path: '/review'
      fullPath: '/setup/review'
      preLoaderRoute: typeof SetupReviewRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/setup/organization': {
      id: '/setup/organization'
      path: '/organization'
      fullPath: '/setup/organization'
      preLoaderRoute: typeof SetupOrganizationRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/setup/inventory': {
      id: '/setup/inventory'
      path: '/inventory'
      fullPath: '/setup/inventory'
      preLoaderRoute: typeof SetupInventoryRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/setup/import': {
      id: '/setup/import'
      path: '/import'
      fullPath: '/setup/import'
      preLoaderRoute: typeof SetupImportRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/setup/branding': {
      id: '/setup/branding'
      path: '/branding'
      fullPath: '/setup/branding'
      preLoaderRoute: typeof SetupBrandingRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteRouteImport
      parentRoute: typeof AppProductsRouteRoute
    }
    '/_app/products/new/': {
      id: '/_app/products/new/'
      path: '/'
      fullPath: '/products/new/'
      preLoaderRoute: typeof AppProductsNewIndexRouteImport
      parentRoute: typeof AppProductsNewRouteRoute
    }
    '/_app/products/new/suppliers': {
      id: '/_app/products/new/suppliers'
      path: '/suppliers'
      fullPath: '/products/new/suppliers'
      preLoaderRoute: typeof AppProductsNewSuppliersRouteImport
      parentRoute: typeof AppProductsNewRouteRoute
    }
    '/_app/products/new/review': {
      id: '/_app/products/new/review'
      path: '/review'
      fullPath: '/products/new/review'
      preLoaderRoute: typeof AppProductsNewReviewRouteImport
      parentRoute: typeof AppProductsNewRouteRoute
    }
    '/_app/products/new/inventory': {
      id: '/_app/products/new/inventory'
      path: '/inventory'
      fullPath: '/products/new/inventory'
      preLoaderRoute: typeof AppProductsNewInventoryRouteImport
      parentRoute: typeof AppProductsNewRouteRoute
    }
    '/_app/products/new/customers': {
      id: '/_app/products/new/customers'
      path: '/customers'
      fullPath: '/products/new/customers'
      preLoaderRoute: typeof AppProductsNewCustomersRouteImport
      parentRoute: typeof AppProductsNewRouteRoute
    }
  }
}

interface SetupRouteRouteChildren {
  SetupBrandingRoute: typeof SetupBrandingRoute
  SetupImportRoute: typeof SetupImportRoute
  SetupInventoryRoute: typeof SetupInventoryRoute
  SetupOrganizationRoute: typeof SetupOrganizationRoute
  SetupReviewRoute: typeof SetupReviewRoute
  SetupTeamRoute: typeof SetupTeamRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteRouteChildren: SetupRouteRouteChildren = {
  SetupBrandingRoute: SetupBrandingRoute,
  SetupImportRoute: SetupImportRoute,
  SetupInventoryRoute: SetupInventoryRoute,
  SetupOrganizationRoute: SetupOrganizationRoute,
  SetupReviewRoute: SetupReviewRoute,
  SetupTeamRoute: SetupTeamRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteRouteWithChildren = SetupRouteRoute._addFileChildren(
  SetupRouteRouteChildren,
)

interface AppProductsNewRouteRouteChildren {
  AppProductsNewCustomersRoute: typeof AppProductsNewCustomersRoute
  AppProductsNewInventoryRoute: typeof AppProductsNewInventoryRoute
  AppProductsNewReviewRoute: typeof AppProductsNewReviewRoute
  AppProductsNewSuppliersRoute: typeof AppProductsNewSuppliersRoute
  AppProductsNewIndexRoute: typeof AppProductsNewIndexRoute
}

const AppProductsNewRouteRouteChildren: AppProductsNewRouteRouteChildren = {
  AppProductsNewCustomersRoute: AppProductsNewCustomersRoute,
  AppProductsNewInventoryRoute: AppProductsNewInventoryRoute,
  AppProductsNewReviewRoute: AppProductsNewReviewRoute,
  AppProductsNewSuppliersRoute: AppProductsNewSuppliersRoute,
  AppProductsNewIndexRoute: AppProductsNewIndexRoute,
}

const AppProductsNewRouteRouteWithChildren =
  AppProductsNewRouteRoute._addFileChildren(AppProductsNewRouteRouteChildren)

interface AppProductsRouteRouteChildren {
  AppProductsNewRouteRoute: typeof AppProductsNewRouteRouteWithChildren
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppProductsRouteRouteChildren: AppProductsRouteRouteChildren = {
  AppProductsNewRouteRoute: AppProductsNewRouteRouteWithChildren,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppProductsRouteRouteWithChildren =
  AppProductsRouteRoute._addFileChildren(AppProductsRouteRouteChildren)

interface AppRouteChildren {
  AppProductsRouteRoute: typeof AppProductsRouteRouteWithChildren
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProductsRouteRoute: AppProductsRouteRouteWithChildren,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SetupRouteRoute: SetupRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
