/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SetupRouteRouteImport } from './routes/setup/route'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as SetupTeamRouteImport } from './routes/setup/team'
import { Route as SetupReviewRouteImport } from './routes/setup/review'
import { Route as SetupOrganizationRouteImport } from './routes/setup/organization'
import { Route as SetupInventoryRouteImport } from './routes/setup/inventory'
import { Route as SetupImportRouteImport } from './routes/setup/import'
import { Route as SetupBrandingRouteImport } from './routes/setup/branding'
import { Route as AppSuppliersRouteImport } from './routes/_app/suppliers'
import { Route as AppProductsRouteImport } from './routes/_app/products'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRouteRoute = SetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SetupTeamRoute = SetupTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SetupRouteRoute,
} as any)
const SetupReviewRoute = SetupReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => SetupRouteRoute,
} as any)
const SetupOrganizationRoute = SetupOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => SetupRouteRoute,
} as any)
const SetupInventoryRoute = SetupInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => SetupRouteRoute,
} as any)
const SetupImportRoute = SetupImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => SetupRouteRoute,
} as any)
const SetupBrandingRoute = SetupBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => SetupRouteRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/setup': typeof SetupRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/products': typeof AppProductsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/setup/branding': typeof SetupBrandingRoute
  '/setup/import': typeof SetupImportRoute
  '/setup/inventory': typeof SetupInventoryRoute
  '/setup/organization': typeof SetupOrganizationRoute
  '/setup/review': typeof SetupReviewRoute
  '/setup/team': typeof SetupTeamRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRoutesByTo {
  '/products': typeof AppProductsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/setup/branding': typeof SetupBrandingRoute
  '/setup/import': typeof SetupImportRoute
  '/setup/inventory': typeof SetupInventoryRoute
  '/setup/organization': typeof SetupOrganizationRoute
  '/setup/review': typeof SetupReviewRoute
  '/setup/team': typeof SetupTeamRoute
  '/': typeof AppIndexRoute
  '/setup': typeof SetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/setup': typeof SetupRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_app/products': typeof AppProductsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/setup/branding': typeof SetupBrandingRoute
  '/setup/import': typeof SetupImportRoute
  '/setup/inventory': typeof SetupInventoryRoute
  '/setup/organization': typeof SetupOrganizationRoute
  '/setup/review': typeof SetupReviewRoute
  '/setup/team': typeof SetupTeamRoute
  '/_app/': typeof AppIndexRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/setup'
    | '/'
    | '/products'
    | '/suppliers'
    | '/setup/branding'
    | '/setup/import'
    | '/setup/inventory'
    | '/setup/organization'
    | '/setup/review'
    | '/setup/team'
    | '/setup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/products'
    | '/suppliers'
    | '/setup/branding'
    | '/setup/import'
    | '/setup/inventory'
    | '/setup/organization'
    | '/setup/review'
    | '/setup/team'
    | '/'
    | '/setup'
  id:
    | '__root__'
    | '/setup'
    | '/_app'
    | '/_app/products'
    | '/_app/suppliers'
    | '/setup/branding'
    | '/setup/import'
    | '/setup/inventory'
    | '/setup/organization'
    | '/setup/review'
    | '/setup/team'
    | '/_app/'
    | '/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SetupRouteRoute: typeof SetupRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/setup/team': {
      id: '/setup/team'
      path: '/team'
      fullPath: '/setup/team'
      preLoaderRoute: typeof SetupTeamRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/setup/review': {
      id: '/setup/review'
      path: '/review'
      fullPath: '/setup/review'
      preLoaderRoute: typeof SetupReviewRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/setup/organization': {
      id: '/setup/organization'
      path: '/organization'
      fullPath: '/setup/organization'
      preLoaderRoute: typeof SetupOrganizationRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/setup/inventory': {
      id: '/setup/inventory'
      path: '/inventory'
      fullPath: '/setup/inventory'
      preLoaderRoute: typeof SetupInventoryRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/setup/import': {
      id: '/setup/import'
      path: '/import'
      fullPath: '/setup/import'
      preLoaderRoute: typeof SetupImportRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/setup/branding': {
      id: '/setup/branding'
      path: '/branding'
      fullPath: '/setup/branding'
      preLoaderRoute: typeof SetupBrandingRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface SetupRouteRouteChildren {
  SetupBrandingRoute: typeof SetupBrandingRoute
  SetupImportRoute: typeof SetupImportRoute
  SetupInventoryRoute: typeof SetupInventoryRoute
  SetupOrganizationRoute: typeof SetupOrganizationRoute
  SetupReviewRoute: typeof SetupReviewRoute
  SetupTeamRoute: typeof SetupTeamRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteRouteChildren: SetupRouteRouteChildren = {
  SetupBrandingRoute: SetupBrandingRoute,
  SetupImportRoute: SetupImportRoute,
  SetupInventoryRoute: SetupInventoryRoute,
  SetupOrganizationRoute: SetupOrganizationRoute,
  SetupReviewRoute: SetupReviewRoute,
  SetupTeamRoute: SetupTeamRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteRouteWithChildren = SetupRouteRoute._addFileChildren(
  SetupRouteRouteChildren,
)

interface AppRouteChildren {
  AppProductsRoute: typeof AppProductsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProductsRoute: AppProductsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SetupRouteRoute: SetupRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
